added a question if the cso has an office
whilesmart/lasodec pull request #161
Opened 2023-08-04 13:48 UTC by jpenanje

2023-08-05 15:19 UTC, Fenn-CS requested changes
I can't see the database migration, For these new fields.

2023-08-05 21:20 UTC, Fenn-CS requested changes
Add all the 3 new columns in a single migration. (I think it's better that way).

2023-08-05 23:13 UTC, Fenn-CS commented on database/migrations/2023_08_05_230419_add_fields_to_cso_registration_form.php
> +            Schema::dropIfExists('csos');
The down method is the opposite of up! In this case, you added 3 rows, so in the down function you should delete/remove/undo the 3 columns.

Dropping the table would be fine if this migration was the first to introduce it.

2023-08-05 23:14 UTC, Fenn-CS reviewed
1 more comment

2023-08-07 12:51 UTC, jpenanje commented
> The number of staff selected when creating a cso on the frontend do not reflect in the cso dashboard edit page

The errors have been rectified.

'three-ten' => '3 - 10'  instead of 'three - ten' => '3 - 10' 
'eleven-fifty' => '11 - 50' 'eleven - fifty' => '11 - 50'

2023-08-09 08:43 UTC, ExcelDurant approved these changes

2023-08-09 10:55 UTC, ExcelDurant approved these changes

2023-08-09 11:02 UTC, Fenn-CS approved these changes

2023-08-09 11:03 UTC, merged