Implement i18n for English and French support
whilesmart/lasodec pull request #20
Opened 2023-06-15 19:29 UTC by ExcelDurant

This PR includes the addition of English and French translations for the initial messages in a Laravel project. The `lang` directory was created to house the translations for the project in two different languages: `en` and `fr`. 

The initial directories and translations were generated by running the `php artisan lang:publish` command. The French translations were then added to the appropriate files. 

closes #11

2023-06-24 13:14 UTC, Fenn-CS commented on config/app.php
> +    'fallback_locale' => 'fr',
Why?

2023-06-24 13:15 UTC, Fenn-CS requested changes
There should probably be a place in the header to make the language switch.

2023-06-25 21:45 UTC, Fenn-CS requested changes
Please let's use translation strings. Managing these keys usually grow out of hand.

See : https://laravel.com/docs/10.x/localization#using-translation-strings-as-keys

Also one should be able to use the button in the header to switch languages

2023-06-28 11:07 UTC, Fenn-CS commented on lang/en/passwords.php
> +    'reset' => 'Your password has been reset.',
```suggestion
    'Your password has been reset.' => 'Your password has been reset.',
```

I mentioned in a previous review that you should use the translation strings as the keys. Do this everywhere.


https://laravel.com/docs/10.x/localization#using-translation-strings-as-keys

2023-06-28 11:07 UTC, Fenn-CS requested changes
See inline

2023-06-30 11:34 UTC, Fenn-CS commented on lang/en/passwords.php
> +    'reset' => 'Your password has been reset.',
Search if you can regenerate them in the particular way discussed or if you can copy them from somewhere. 

Finish this so translation work can proceed.

2023-06-30 16:20 UTC, Fenn-CS reviewed
Have you tested this? Did the translation work with the default messages? for example the ones on auth forms?

2023-06-30 16:20 UTC, Fenn-CS commented on lang/en/home.php
> +    'our helping' => 'Our Helping',
```suggestion
    'Our helping' => 'Our Helping',
```


Or is it required to be in lowercase ?

2023-06-30 18:26 UTC, ExcelDurant commented
> Have you tested this? Did the translation work with the default messages? for example the ones on auth forms?

The French validation translations seem not to work with translation strings. I am still looking for a solution to this issue

2023-07-02 10:43 UTC, Fenn-CS approved these changes

2023-07-02 10:43 UTC, merged