Replace placeholder text with requirements text
whilesmart/lasodec pull request #34
Opened 2023-06-25 13:19 UTC by ExcelDurant

closes #12

2023-06-25 16:38 UTC, Fenn-CS requested changes
- There a conflict?
- We should use language files because the site has to be available in two languages?

2023-06-26 00:06 UTC, slpat approved these changes

2023-06-26 15:51 UTC, ExcelDurant commented
The pull request concerning `i18n` needs to be merged before this pull request can be fully updated

2023-07-03 20:19 UTC, Fenn-CS commented
@ExcelDurant I guess this can now be updated?

2023-07-04 09:56 UTC, Fenn-CS approved these changes

2023-07-04 09:56 UTC, merged